name: hypelify
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.17+47

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  go_router: ^14.8.1
  provider: ^6.0.5
  get_it: ^8.0.3
  shared_preferences: ^2.1.1
  photo_view: ^0.15.0
  flutter_screenutil: ^5.7.0
  mvc_pattern: ^8.12.0
  equatable: ^2.0.5
  internet_connection_checker_plus: ^2.0.0
  dartz: ^0.10.1
  http: ^1.0.0
  flutter_svg: ^2.0.5
  intl: ^0.19.0
  google_fonts: ^6.2.1
  url_launcher: ^6.1.10
  flutter_colorpicker: ^1.0.3
  ansicolor: ^2.0.2
  introduction_screen: ^3.1.12
  country_code_picker: ^3.0.0
  fluttertoast: ^8.2.4
  animate_do: ^4.2.0
  firebase_core: ^3.12.1
  firebase_messaging: ^15.2.4
  firebase_dynamic_links: ^6.1.4
  unique_identifier: ^0.4.0
  pin_code_fields: ^8.0.1
  google_maps_flutter: ^2.5.3
  geolocator: ^13.0.2
  geocoding: ^3.0.0
  flutter_google_places: ^0.3.0
  pull_to_refresh: ^2.0.0
  permission_handler: ^11.4.0
  appinio_social_share: ^0.3.2
  share_plus:
  cached_network_image: ^3.2.3
  in_app_update: ^4.2.2
  comment_tree: ^0.3.0
  better_player: ^0.0.83
  like_button: ^2.0.5
  image_picker: ^1.1.2
  video_thumbnail: 0.5.3
  qr_flutter: ^4.0.0
  font_awesome_flutter: ^10.3.0
  collection: ^1.18.0
  timeago: ^3.6.1
  open_file: ^3.3.2






flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/hypelify.png"
  min_sdk_android: 21 # an

dependency_overrides:
  intl: ^0.18.0
  win32: 4.0.0
  http: ^0.13.5


dev_dependencies:
  flutter_test:
    sdk: flutter
#  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - i18n/

