// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqS8-9b-_NhjgmdyW5cd3AbtsgnpxW7LI',
    appId: '1:228486605253:web:e7230d774af33d4cbb83ac',
    messagingSenderId: '228486605253',
    projectId: 'hypelify-app',
    authDomain: 'hypelify-app.firebaseapp.com',
    storageBucket: 'hypelify-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1SJLivJMKNCxiWH1e7rKjvjZK5I9xFSE',
    appId: '1:228486605253:android:3cda412cdb341924bb83ac',
    messagingSenderId: '228486605253',
    projectId: 'hypelify-app',
    storageBucket: 'hypelify-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALWbCSU24D19I6LfQp9EzMHjnKv9T9vJE',
    appId: '1:228486605253:ios:80af65d49362eefdbb83ac',
    messagingSenderId: '228486605253',
    projectId: 'hypelify-app',
    storageBucket: 'hypelify-app.appspot.com',
    iosBundleId: 'com.hypelifyapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALWbCSU24D19I6LfQp9EzMHjnKv9T9vJE',
    appId: '1:228486605253:ios:4adbc0b2aa43e7f9bb83ac',
    messagingSenderId: '228486605253',
    projectId: 'hypelify-app',
    storageBucket: 'hypelify-app.appspot.com',
    iosBundleId: 'com.hypelify.hypelify.hypelifyapp.RunnerTests',
  );
}
